services:
  paas-rabbitmq:
    container_name: paas-rabbitmq
    hostname: rabbitmq
    image: rabbitmq:3.13.6-management
    # image: 'bitnami/rabbitmq:3.11.8-debian-11-r0'
    environment:
      - RABBITMQ_DEFAULT_USER=admin    # RabbitMQ yönetici kullanıcı adı
      - RABBITMQ_DEFAULT_PASS=admin    # RabbitMQ yönetici kullanıcı şifresi
      - RABBITMQ_VHOST='/'             # RabbitMQ kullanıcı için sanal ana bilgisayar adı (RabbitMQ yönetici kullanıcı için sanal ana bilgisayar adı ile aynı olmamalı)
      - RABBITMQ_PLUGINS="rabbitmq_management" # RabbitMQ eklentileri (örneğin, yönetim eklentisi)
      - RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS=true # Allow web access to RabbitMQ management portal for RABBITMQ_USERNAME
    ports:
       # amqp: 5672
       # amqpTls: 5671
       # dist: 25672
       # manager: 15672
       # epmd: 4369
       # metrics: 9419
      - "5672:5672"   # AMQP protokolü için standart port
      - "15672:15672" # Web tabanlı yönetim arayüzü için port
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
    networks:
      privnet:
        ipv4_address: "10.100.100.2"
        aliases:
          - rabbit.ulakhaberlesme.com.tr

  paas-mongo:
    container_name: paas-mongo
    hostname: mongo
    image: mongo
    command: mongod --port 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: cnrusr
      MONGO_INITDB_ROOT_PASSWORD: P5vKG6vE
      MONGO_INITDB_DATABASE: cinarnrftest
    expose:
      - "27017"
    networks:
      privnet:
        ipv4_address: "10.100.100.3"
        aliases:
          - mongo.ulakhaberlesme.com.tr

  paas-mongo-express:
    image: mongo-express # https://hub.docker.com/_/mongo-express
    container_name: paas-mongo-express
    restart: always
    networks:
      privnet:
        ipv4_address: "10.100.100.4"
        aliases:
          - mongo-express.ulakhaberlesme.com.tr
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://cnrusr:P5vKG6vE@mongo.ulakhaberlesme.com.tr:27017/
      ME_CONFIG_MONGODB_ADMINUSERNAME: cnrusr # GUI kullanıcı adı
      ME_CONFIG_MONGODB_ADMINPASSWORD: P5vKG6vE # GUI kullanıcı şifresi
      ME_CONFIG_BASICAUTH: false
      ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
    depends_on:
      - paas-mongo

  ulak-nrf:
    container_name: ulak-nrf
    image: registry.ulakhaberlesme.com.tr/cinar/nrf/monolith:latest-stable-xenial
    expose:
      - 8000
      - 8001
      - 8005
      - 8006
      - 8007
      - 8009
      - 8010
    volumes:
      - ./config/nrf-settings.json:/opt/cinar/nrf/settings.json
      - ./config/nrf-NFProfile.json:/opt/cinar/nrf/NFProfile.json
      - ./cert:/opt/cinar/certificate
      - ./cert:/opt/cinar/nrf/certificate
    environment:
      DB_URI: mongodb://ulak-mongodb/free5gc
      GIN_MODE: release
    networks:
      privnet:
        ipv4_address: "10.100.100.5"
        aliases:
          - nrf.ulakhaberlesme.com.tr
    healthcheck:
      test: ["CMD-SHELL", "grep -q 'DB connection is successful' /var/log/cinar/nrf/NRF.log"]
      interval: 10s
      retries: 10
      start_period: 30s
      timeout: 5s
    depends_on:
      - paas-mongo

  ulak-amf:
    container_name: ulak-amf
    image: registry.ulakhaberlesme.com.tr/cinar/amf/monolith:latest-stable-xenial
    expose:
      - 6286
      - 6210
      - 6211
      - 6212
      - 6213
      - 6224
      - 6287
      - 6290
      - 38412
    volumes:
      - ./config/amf-settings.json:/opt/cinar/amf/settings.json
      - ./cert/:/opt/cinar/certificate
      - ./cert/:/opt/cinar/amf/certificate
    environment:
      GIN_MODE: release
    networks:
      privnet:
        ipv4_address: "10.100.100.6"
        aliases:
          - amf.ulakhaberlesme.com.tr
    healthcheck:
      test: ["CMD-SHELL", "cat /proc/net/sctp/eps | grep -q 38412"]
      interval: 10s
      retries: 10
      start_period: 30s
      timeout: 5s
    depends_on:
      ulak-nrf:
        condition: service_healthy
      paas-rabbitmq:
        condition: service_healthy

  ueransim:
    container_name: ueransim
    image: free5gc/ueransim:latest
    command: ./nr-gnb -c ./config/gnbcfg.yaml
    volumes:
      - ./config/ulak-gnb.yaml:/ueransim/config/gnbcfg.yaml
      - ./config/ulak-ue.yaml:/ueransim/config/uecfg.yaml
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    networks:
      privnet:
        ipv4_address: "10.100.100.7"
        aliases:
          - gnb.ulakhaberlesme.com.tr
    depends_on:
      ulak-amf:
        condition: service_healthy

networks:
  privnet:
    name: ulak-privnet
    ipam:
      driver: default
      config:
        - subnet: 10.100.100.0/24
    driver_opts:
      com.docker.network.bridge.name: br-ulak
