services:
  paas-rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:3.13.6-management
    # image: 'bitnami/rabbitmq:3.11.8-debian-11-r0'
    environment:
      - RABBITMQ_DEFAULT_USER=admin    # RabbitMQ yönetici kullanıcı adı
      - RABBITMQ_DEFAULT_PASS=admin    # RabbitMQ yönetici kullanıcı şifresi
      - RABBITMQ_VHOST='/'             # RabbitMQ kullanıcı için sanal ana bilgisayar adı (RabbitMQ yönetici kullanıcı için sanal ana bilgisayar adı ile aynı olmamalı)
      - RABBITMQ_PLUGINS="rabbitmq_management" # RabbitMQ eklentileri (örneğin, yönetim eklentisi)
      - RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS=true # Allow web access to RabbitMQ management portal for RABBITMQ_USERNAME
    ports:
       # amqp: 5672
       # amqpTls: 5671
       # dist: 25672
       # manager: 15672
       # epmd: 4369
       # metrics: 9419
      - "5672:5672"   # AMQP protokolü için standart port
      - "15672:15672" # Web tabanlı yönetim arayüzü için port
    networks:
      privnet:
        aliases:
          - rabbit.ulakhaberlesme.com.tr

  paas-mongo:
    container_name: ulak-mongodb
    image: mongo
    command: mongod --port 27017
    expose:
      - "27017"
    networks:
      privnet:
        aliases:
          - mongo.ulakhaberlesme.com.tr

  ulak-nrf:
    container_name: ulak-nrf
    image: registry.ulakhaberlesme.com.tr/cinar/nrf/monolith:latest-stable-xenial
    expose:
      - 8000
      - 8001
      - 8005
      - 8006
      - 8007
      - 8009
      - 8010
    volumes:
      - ./config/nrf-settings.json:/opt/cinar/nrf/settings.json
      - ./config/nrf-NFProfile.json:/opt/cinar/nrf/NFProfile.json
      - ./cert/:/opt/cinar/certificate
      - ./cert/:/opt/cinar/nrf/certificate
    environment:
      DB_URI: mongodb://ulak-mongodb/free5gc
      GIN_MODE: release
    networks:
      privnet:
        aliases:
          - nrf.ulakhaberlesme.com.tr
    depends_on:
      - paas-mongo

  ulak-amf:
    container_name: ulak-amf
    image: registry.ulakhaberlesme.com.tr/cinar/amf/monolith:latest-stable-xenial-dbg
    expose:
      - 6286
      - 6210
      - 6211
      - 6212
      - 6213
      - 6224
      - 6287
      - 6290
      - 38412
    volumes:
      - ./ulak-amf.yaml:/free5gc/config/amfcfg.yaml
      - ./cert/:/opt/cinar/certificate
      - ./cert/:/opt/cinar/amf/certificate
    environment:
      GIN_MODE: release
    networks:
      privnet:
        aliases:
          - amf.ulakhaberlesme.com.tr
    depends_on:
      - paas-rabbitmq
      - paas-mongo
      - ulak-nrf

  ueransim:
    container_name: ueransim
    image: free5gc/ueransim:latest
    command: ./nr-gnb -c ./config/gnbcfg.yaml
    volumes:
      - ./ulak-gnb.yaml:/ueransim/config/gnbcfg.yaml
      - ./ulak-ue.yaml:/ueransim/config/uecfg.yaml
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun"
    networks:
      privnet:
        # ipv4_address: 10.100.200.3
        aliases:
          - gnb.ulakhaberlesme.com.tr
    depends_on:
      - ulak-amf
      # - ulak-upf

networks:
  privnet:
    ipam:
      driver: default
      config:
        - subnet: 10.100.100.0/24
    driver_opts:
      com.docker.network.bridge.name: br-ulak
