# IMSI number of the UE. IMSI = [MCC|MNC|MSISDN] (In total 15 digits)
# ===ilk aşamada supi postgres'e import ediliyor; ===
# ===UDR db'sinde AccessAndMobilitySubscriptionData; ===
supi: 'imsi-001002001000069'
# Mobile Country Code value of HPLMN
mcc: '001'
# Mobile Network Code value of HPLMN (2 or 3 digits)
mnc: '002'
# SUCI Protection Scheme : 0 for Null-scheme, 1 for Profile A and 2 for Profile B
# === supi hava arayüzünden giderken şifrelimi şifresiz mi gitmesi gerektiğini belirtir ===
protectionScheme: 0
# === protectionScheme: 0 olduğu için keylere gerek olmadığı için kapatıyoruz ===
# # Home Network Public Key for protecting with SUCI Profile A
# homeNetworkPublicKey: '5a8d38864820197c3394b92613b20b91633cbd897119273bf8e4a6f4eec0a650'
# # Home Network Public Key ID for protecting with SUCI Profile A
# homeNetworkPublicKeyId: 1
# # Routing Indicator
# routingIndicator: '0000'

# Permanent subscription key
# === UDR DB'de AuthenticationSubscription collection'ununda bulunan AuthData kolonunda encPermanentKey ===
key: 'FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF'
# Operator code (OP or OPC) of the UE
# === UDM settings'i içerisinde OperatorVariant ===
op: '00000000000000000000000000000000'
# This value specifies the OP type and it can be either 'OP' or 'OPC'
opType: 'OP'
# Authentication Management Field (AMF) value
amf: '8000'
# IMEI number of the device. It is used if no SUPI is provided
imei: '356938035643803'
# IMEISV number of the device. It is used if no SUPI and IMEI is provided
imeiSv: '4370816125816151'

# List of gNB IP addresses for Radio Link Simulation
gnbSearchList:
  - 0.0.0.0

# UAC Access Identities Configuration
uacAic:
  mps: false
  mcs: false

# UAC Access Control Class
uacAcc:
  normalClass: 0
  class11: false
  class12: false
  class13: false
  class14: false
  class15: false

# Initial PDU sessions to be established
sessions:
  - type: 'IPv4'
    apn: 'dnn.test1.com' # ulak default dnn
    slice:
      sst: 1
      sd: 1

# Configured NSSAI for this UE by HPLMN
configured-nssai:
  - sst: 1
    sd: 1

# Default Configured NSSAI for this UE
default-nssai:
  - sst: 1
    sd: 1

# Supported integrity algorithms by this UE
integrity:
  IA1: true
  IA2: true
  IA3: true

# Supported encryption algorithms by this UE
ciphering:
  EA1: true
  EA2: true
  EA3: true

# Integrity protection maximum data rate for user plane
integrityMaxRate:
  uplink: 'full'
  downlink: 'full'
